import React, { useState, useEffect, useRef } from 'react';
import { useParams, useSearchParams, Link } from 'react-router-dom';
import { Check, Calendar, MapPin, AlertTriangle, Ticket as TicketIcon } from 'lucide-react';
import { eventsAPI } from '@/services/index';
import { formatMoney } from '@/utils/currency';
import InterflowLogo from '@/components/common/InterflowLogo';

const GOLD = '#8D5D1D';

/* Poll while the Paystack webhook is still in flight. */
const POLL_INTERVAL_MS = 2500;
const POLL_TIMEOUT_MS  = 90000;

const fmtDate = (d) =>
  d ? new Date(d).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' }) : '';

/* ─── Single digital ticket (§13) ───────────────────────────────── */
const DigitalTicket = ({ ticket, order }) => (
  <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
    <div className="px-5 py-4 flex items-center gap-3" style={{ background: GOLD }}>
      <TicketIcon size={18} className="text-white shrink-0" />
      <div className="min-w-0">
        <p className="text-white font-bold text-[14px] truncate">{order.event_name}</p>
        <p className="text-white/70 text-[12px]">{ticket.ticket_type_name}</p>
      </div>
    </div>

    <div className="p-5 flex flex-col items-center gap-4">
      {/* QR — generated by the backend so the payload stays opaque (§14) */}
      {ticket.qr_image_url ? (
        <img src={ticket.qr_image_url} alt={`QR code for ticket ${ticket.ticket_id}`}
          className="w-[180px] h-[180px] object-contain" />
      ) : (
        <div className="w-[180px] h-[180px] rounded-xl bg-gray-50 border border-dashed border-gray-200 flex flex-col items-center justify-center gap-2 text-center px-4">
          <TicketIcon size={26} className="text-gray-300" />
          <p className="text-[11.5px] text-gray-400 leading-snug">QR code will appear here once issued</p>
        </div>
      )}

      <div className="w-full flex flex-col gap-2 border-t border-dashed border-gray-200 pt-4">
        {[
          ['Attendee', ticket.attendee_name || order.customer_name],
          ['Ticket ID', ticket.ticket_id],
          ['Date', fmtDate(order.event_date)],
          ['Venue', [order.venue_name, order.city].filter(Boolean).join(', ')],
        ].filter(([, v]) => v).map(([k, v]) => (
          <div key={k} className="flex justify-between gap-4 text-[13px]">
            <span className="text-gray-400 shrink-0">{k}</span>
            <span className="text-gray-800 font-medium text-right break-all">{v}</span>
          </div>
        ))}
      </div>

      {ticket.status && ticket.status !== 'valid' && (
        <span className="text-[11px] font-bold uppercase tracking-wide px-3 py-1 rounded-full bg-red-50 text-red-600">
          {ticket.status}
        </span>
      )}
    </div>
  </div>
);

/* ─── Status screens ────────────────────────────────────────────── */
const Centered = ({ children }) => (
  <div className="min-h-screen flex flex-col" style={{ background: '#F4F2EE' }}>
    <header className="bg-white border-b border-gray-100 px-5 sm:px-6 py-3">
      <InterflowLogo variant="dark" style={{ height: 34, width: 'auto' }} />
    </header>
    <div className="flex-1 flex items-center justify-center px-4 py-10">
      <div className="w-full max-w-[520px]">{children}</div>
    </div>
  </div>
);

/* ═══════════════════════════════════════════════════════════════
   Order Confirmation (§11, §12, §13)

   The browser is NEVER treated as proof of payment. Landing here only
   means Paystack redirected us back — the order is authoritative only
   once the backend has verified the webhook, so we poll until it does.
   ═══════════════════════════════════════════════════════════════ */
const OrderConfirmationPage = () => {
  const { reference: paramRef } = useParams();
  const [searchParams] = useSearchParams();
  /* Paystack appends ?reference= / ?trxref= on redirect. */
  const reference = paramRef || searchParams.get('reference') || searchParams.get('trxref');

  const [order, setOrder]     = useState(null);
  const [error, setError]     = useState(null);
  const [timedOut, setTimedOut] = useState(false);
  const startedAt = useRef(Date.now());

  useEffect(() => {
    if (!reference) { setError('No order reference was provided.'); return; }

    let alive = true;
    let timer;

    const poll = async () => {
      try {
        const r = await eventsAPI.orderStatus(reference);
        if (!alive) return;
        const d = r.data?.data || r.data || {};
        setOrder(d);

        /* Settled — stop polling. */
        if (['successful', 'failed', 'cancelled', 'refunded'].includes(d.payment_status)) return;

        if (Date.now() - startedAt.current > POLL_TIMEOUT_MS) { setTimedOut(true); return; }
        timer = setTimeout(poll, POLL_INTERVAL_MS);
      } catch {
        if (!alive) return;
        /* Order may not be visible for a beat — keep trying within the window. */
        if (Date.now() - startedAt.current > POLL_TIMEOUT_MS) {
          setError('We could not confirm this order. Please contact support.');
          return;
        }
        timer = setTimeout(poll, POLL_INTERVAL_MS);
      }
    };

    poll();
    return () => { alive = false; clearTimeout(timer); };
  }, [reference]);

  /* ── Hard error ── */
  if (error) {
    return (
      <Centered>
        <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-8 text-center">
          <div className="w-14 h-14 rounded-full bg-red-50 flex items-center justify-center mx-auto mb-4">
            <AlertTriangle size={24} className="text-red-500" />
          </div>
          <h1 className="font-bold text-[20px] text-gray-900 mb-2">Something went wrong</h1>
          <p className="text-[14px] text-gray-500 mb-6">{error}</p>
          <Link to="/" className="text-[14px] font-semibold hover:underline" style={{ color: GOLD }}>
            Go to Interflow
          </Link>
        </div>
      </Centered>
    );
  }

  /* ── Waiting on webhook verification ── */
  if (!order || (order.payment_status === 'pending' && !timedOut)) {
    return (
      <Centered>
        <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-10 text-center">
          <div className="mx-auto mb-5" style={{ width: 44, height: 44, border: '3px solid rgba(141,93,29,0.15)', borderTopColor: GOLD, borderRadius: '50%', animation: 'spin 0.7s linear infinite' }} />
          <h1 className="font-bold text-[19px] text-gray-900 mb-2">Confirming your payment…</h1>
          <p className="text-[14px] text-gray-500 leading-relaxed">
            This usually takes a few seconds. Please don't close this page.
          </p>
          {reference && <p className="text-[12px] text-gray-400 mt-4">Reference: {reference}</p>}
        </div>
      </Centered>
    );
  }

  /* ── Verification still not through after the timeout ── */
  if (timedOut && order.payment_status === 'pending') {
    return (
      <Centered>
        <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-8 text-center">
          <div className="w-14 h-14 rounded-full bg-amber-50 flex items-center justify-center mx-auto mb-4">
            <AlertTriangle size={24} className="text-amber-500" />
          </div>
          <h1 className="font-bold text-[20px] text-gray-900 mb-2">Still confirming</h1>
          <p className="text-[14px] text-gray-500 leading-relaxed mb-2">
            Your payment is taking longer than usual to confirm. If it was successful,
            your ticket will be emailed to you shortly — you don't need to pay again.
          </p>
          <p className="text-[12px] text-gray-400 mb-6">Reference: {reference}</p>
          <button onClick={() => window.location.reload()}
            className="px-6 h-11 rounded-full text-white text-[13px] font-semibold" style={{ background: GOLD }}>
            Check again
          </button>
        </div>
      </Centered>
    );
  }

  /* ── Failed / cancelled ── */
  if (['failed', 'cancelled'].includes(order.payment_status)) {
    return (
      <Centered>
        <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-8 text-center">
          <div className="w-14 h-14 rounded-full bg-red-50 flex items-center justify-center mx-auto mb-4">
            <AlertTriangle size={24} className="text-red-500" />
          </div>
          <h1 className="font-bold text-[20px] text-gray-900 mb-2">Payment not completed</h1>
          <p className="text-[14px] text-gray-500 mb-6">
            Your payment was not successful, so no ticket was issued. You have not been charged.
          </p>
          <Link to="/" className="text-[14px] font-semibold hover:underline" style={{ color: GOLD }}>
            Back to Interflow
          </Link>
        </div>
      </Centered>
    );
  }

  /* ── Success ── */
  const tickets = order.tickets || [];

  return (
    <Centered>
      <div className="flex flex-col gap-5">
        {/* Success header */}
        <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-8 text-center">
          <div className="w-16 h-16 rounded-full bg-green-500 flex items-center justify-center mx-auto mb-5">
            <Check size={30} className="text-white" strokeWidth={3} />
          </div>
          <h1 className="font-bold text-gray-900 mb-2"
            style={{ fontFamily: 'Cormorant Garamond, serif', fontSize: 26 }}>
            You're going!
          </h1>
          <p className="text-[14px] text-gray-500 leading-relaxed">
            Your payment was confirmed and your ticket has been issued.
          </p>
          {order.customer_email && (
            <p className="text-[13px] text-gray-400 mt-2">
              A copy has been sent to <span className="font-medium text-gray-600">{order.customer_email}</span>
            </p>
          )}
        </div>

        {/* Order summary (§12) */}
        <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-5">
          <h2 className="font-bold text-[14px] text-gray-900 mb-3">Order Summary</h2>
          <div className="flex flex-col gap-2">
            {[
              ['Order ID', order.order_reference],
              ['Event', order.event_name],
              ['Date', fmtDate(order.event_date)],
              ['Venue', [order.venue_name, order.city].filter(Boolean).join(', ')],
              ['Ticket', order.ticket_type_name && `${order.ticket_type_name} × ${order.quantity}`],
              ['Amount', order.amount != null && formatMoney(order.amount, order.currency)],
            ].filter(([, v]) => v).map(([k, v]) => (
              <div key={k} className="flex justify-between gap-4 text-[13px]">
                <span className="text-gray-400 shrink-0">{k}</span>
                <span className="text-gray-800 font-medium text-right">{v}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Tickets */}
        {tickets.length > 0 && (
          <div className="flex flex-col gap-4">
            <p className="text-[13px] font-semibold text-gray-500 uppercase tracking-wide px-1">
              {tickets.length === 1 ? 'Your Ticket' : `Your Tickets (${tickets.length})`}
            </p>
            {tickets.map(t => <DigitalTicket key={t.ticket_id} ticket={t} order={order} />)}
          </div>
        )}

        <p className="text-[12px] text-gray-400 text-center pb-4">
          Present the QR code at the entrance. Screenshots are fine.
        </p>
      </div>
    </Centered>
  );
};

export default OrderConfirmationPage;
